### ISSUE TITLE
[Lutris] Unable to detect box art if slug and identifier is different

### ISSUE THREAD

**Issue by Anninzy** [Rolv-Apneseth/lib_game_detector#7]
If the `slug` in the game's yaml is different to the game's identifier (which I think is `game_slug` in the yaml file), the box art won't be detected.

I found that this is due to the box art being named as `[identifier].jpg`, and the library is looking for box art with `[slug].jpg`.

This causes issue if the two are not the same, as in the case with osu's lazer version. Its identifier is set to `osu` but the slug is `osu-osulazer`, as the library is looking for `osu-osulazer.jpg` but the box art in `coverart` is `osu.jpg`, it's not detected.

It'd be great if this is fixed, thanks.

**Comment by Rolv-Apneseth** [comment]
Ah I see. I'll have a look at fixing that, thanks for opening this

**Comment by Rolv-Apneseth** [comment]
Yeah makes sense I have a lot of those hard-coded. I'll look into that too.

**Comment by Rolv-Apneseth** [comment]
Could you provide me the file for that game at `~/.config/lutris/games/[slug].yml`?

**Comment by Rolv-Apneseth** [comment]
Also it's entry in `~/.cache/lutris/game-paths.json` if you can, thanks

**Comment by Anninzy** [comment]
`~/.config/lutris/games/osu-osulazer-1712998316.yml`:
```
game:
  exe: osu.AppImage
game_slug: osu
name: osu!
script:
  files:
  - appimage: https://github.com/ppy/osu/releases/latest/download/osu.AppImage
  game:
    exe: osu.AppImage
  installer:
  - move:
      dst: $GAMEDIR
      src: appimage
  - chmodx: osu.AppImage
slug: osu-osulazer
version: osu!lazer
year: 2007
```

`~/.cache/lutris/game-paths.json`:
```
{
  "1": "/home/owner/Games/osu/osu.AppImage",
  ...
}
```
